[package]
name = "verdantd"
version = "0.1.0"
edition = "2024"

[dependencies]
bloom = { path = "../bloom" }
libc = "0.2.174"
nix = { version = "0.30.1", features = ["signal", "term", "user"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
